---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-pv
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-gz1